### ISSUE TITLE
Libc based on musl?

### ISSUE THREAD

**Issue by lachlansneff** [WebAssembly/wasi-libc-old#7]
To avoid having to reimplement the entirety of libc for the reference-sysroot, I propose we take the environment-agnostic parts of musl and move them here. Musl is licensed under MIT.

**Comment by pchickey** [comment]
We (fastly) have implemented some of the things needed to hook musl up to our webassembly runtime. Another one is at https://github.com/jfbastien/musl.

We are planning to open source our stuff Real Soon Now and I will see if I can give you the source to just the musl stuff if you want to look at how we did it.

**Comment by sunfishcode** [comment]
We now have a musl-derived libc port here: https://github.com/WebAssembly/reference-sysroot/pull/11

**Comment by pchickey** [comment]
and as an update to the above, we ditched our implementation in favor of WASI, and are open sourcing tomorrow.

**Comment by sunfishcode** [comment]
This is now implemented!
